# Generated by Django 4.2.1 on 2023-06-02 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellidoP', models.CharField(default='', max_length=50)),
                ('apellidoM', models.CharField(default='', max_length=50)),
                ('otro_genero', models.CharField(blank=True, default='', max_length=100)),
                ('fecha_nacimiento', models.CharField(default='', max_length=30)),
                ('curp', models.CharField(default='', max_length=19)),
                ('cp', models.CharField(default='', max_length=8)),
                ('calle', models.CharField(default='', max_length=50)),
                ('colonia', models.CharField(default='', max_length=50)),
                ('ciudad', models.CharField(default='', max_length=50)),
                ('celular', models.CharField(default='', max_length=20)),
                ('imagen', models.ImageField(blank=True, upload_to='perfil_imagen')),
                ('correo_secundario', models.CharField(blank=True, default='', max_length=50)),
                ('edad', models.CharField(blank=True, default='', max_length=5)),
                ('dni', models.CharField(blank=True, default='', max_length=19)),
                ('otra_ocupacion', models.CharField(blank=True, default='', max_length=100)),
                ('institucion', models.CharField(blank=True, default='', max_length=100)),
                ('otro_subsector', models.CharField(blank=True, default='', max_length=100)),
                ('carrera', models.CharField(blank=True, default='', max_length=100)),
                ('otro_como_te_enteraste', models.CharField(blank=True, default='', max_length=100)),
                ('json_temas_de_interes', models.CharField(blank=True, default='', max_length=800)),
                ('otro_tema_de_interes', models.CharField(blank=True, default='', max_length=100)),
                ('ultimo_curso', models.CharField(blank=True, default='', max_length=200)),
                ('terminos_y_condiciones', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'usuarios_userprofile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Como_te_enteraste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estado', models.IntegerField(blank=True, null=True)),
                ('estado', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Numero_Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_empleados', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocupacion', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pais', models.IntegerField(blank=True, null=True)),
                ('pais', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Sectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Sexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=19)),
                ('tipo', models.CharField(blank=True, default='', max_length=19)),
            ],
        ),
        migrations.CreateModel(
            name='Subsectores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subsector', models.CharField(default='', max_length=70)),
                ('sector', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.sectores')),
            ],
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio', models.CharField(default='', max_length=100)),
                ('estado', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.estados')),
            ],
        ),
        migrations.AddField(
            model_name='estados',
            name='pais',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.paises'),
        ),
    ]
